"""Basic-plan step evaluators, feature definitions and the element catalog.

``backtest_engine.basic_runtime`` composes these into a runnable plan; nothing
here imports the runtime, so the layering stays one-way.
"""

from backtest_engine.elements.catalog import (
    COMPARISON_OPERATORS,
    ELEMENT_CATALOG_VERSIONS,
    ELEMENT_CATALOGS,
    ElementCatalog,
    ElementSpec,
    element_catalog,
    supported_feature_versions,
)
from backtest_engine.elements.core import (
    CONDITION_ERROR_REASON,
    INPUT_MISSING_REASON,
    ISO8601_RESOLUTIONS,
    RESOLUTION_PERIODS,
    SUPPORTED_RESOLUTIONS,
    ElementCompatibilityError,
    ElementError,
    ElementEvaluation,
    ElementEvaluationError,
    ElementInputMissing,
    InstrumentInput,
    InstrumentSeries,
    PlanLoadFailure,
    PlanStep,
    SeriesBar,
    StepEvaluator,
    StepOutcome,
    bar_resolution,
    resolution_period,
)
from backtest_engine.elements.features import (
    FEATURE_CATALOG_VERSION,
    FEATURE_REGISTRY,
    FEATURE_VALUE_QUANTUM,
    FEATURE_VALUE_SCALE,
    FEATURE_WORKING_PRECISION,
    RSI_14_DEFINITION,
    FeatureDefinition,
    compute_rsi_14,
    feature_definition,
)
from backtest_engine.elements.orders import (
    SUPPORTED_ALLOCATION_MODES,
    SUPPORTED_ORDER_TYPES,
    SUPPORTED_SIDES,
    TERMINAL_OPERATION,
    OrderCandidate,
    emit_order_candidate,
)


__all__ = [
    "COMPARISON_OPERATORS",
    "CONDITION_ERROR_REASON",
    "ELEMENT_CATALOGS",
    "ELEMENT_CATALOG_VERSIONS",
    "FEATURE_CATALOG_VERSION",
    "FEATURE_REGISTRY",
    "FEATURE_VALUE_QUANTUM",
    "FEATURE_VALUE_SCALE",
    "FEATURE_WORKING_PRECISION",
    "INPUT_MISSING_REASON",
    "ISO8601_RESOLUTIONS",
    "RESOLUTION_PERIODS",
    "RSI_14_DEFINITION",
    "SUPPORTED_ALLOCATION_MODES",
    "SUPPORTED_ORDER_TYPES",
    "SUPPORTED_RESOLUTIONS",
    "SUPPORTED_SIDES",
    "TERMINAL_OPERATION",
    "ElementCatalog",
    "ElementCompatibilityError",
    "ElementError",
    "ElementEvaluation",
    "ElementEvaluationError",
    "ElementInputMissing",
    "ElementSpec",
    "FeatureDefinition",
    "InstrumentInput",
    "InstrumentSeries",
    "OrderCandidate",
    "PlanLoadFailure",
    "PlanStep",
    "SeriesBar",
    "StepEvaluator",
    "StepOutcome",
    "bar_resolution",
    "compute_rsi_14",
    "element_catalog",
    "emit_order_candidate",
    "feature_definition",
    "resolution_period",
    "supported_feature_versions",
]
